name: Auto Translation To GitHub
on:
  schedule:
    - cron: "59 * * * *"

jobs:
  Auto-Translation-To-GitHub:
    name: Auto Translation To GitHub
    runs-on: ubuntu-latest
    environment: PARATRANZ_ENV
    env:
      API_TOKEN: ${{secrets.API_KEY}}
      FILE_PATH: ./
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PROJECT_ID: ${{vars.ID}}
      GIT_PATH: https://github.com/Litchiiiiii/test.git
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub
          pip install requests
      - name: merge main
        run: |
          git init
          git fetch origin
          git config --global user.email "1592282237@qq.com"
          git config --global user.name "Litchiiiiiii"
          git checkout develop 
          git reset --hard main
      - name: Paratranz To zh_cn
        run: |
          python translationToGitHub.py
      - name: Upload To Develop
        run: |
          git config --global pull.rebase true
          git add .
          git commit -m 'paratranz上传'
          git pull origin develop --allow-unrelated-histories
          git push -u origin develop
